import type { Language } from './content';
export interface ImageSettings {
  alt?: Partial<Record<Language, string>>;
  caption?: Partial<Record<Language, string>>;
  desktop?: string;
  tablet?: string;
  mobile?: string;
}
// Chiave = percorso della foto. Aggiungi qui un oggetto per qualsiasi immagine
// di camere, servizi o dintorni. Nessuna modifica al CSS è necessaria.
export const imageSettings: Record<string, ImageSettings> = {
  '/images/bnb/spazi-comuni/cucina-comune-con-ceramiche-siciliane.webp': { desktop: '65% center', tablet: '65% center', mobile: '65% center' },
  '/images/bnb/territorio/panorama-santo-stefano-di-camastra.webp': { desktop: 'center 48%', tablet: 'center 48%', mobile: 'center 48%' },
  '/images/bnb/esperienze/cicloturismo-costa-siciliana.webp': { desktop: 'center', mobile: '65% center', alt: { it: 'Illustrazione fotografica di un ciclista sulla costa siciliana', en: 'Photographic illustration of a cyclist on the Sicilian coast', de: 'Fotografische Illustration eines Radfahrers an der sizilianischen Küste' } },
};

export const nearbyImages = [
  { src: '/images/bnb/territorio/panorama-santo-stefano-di-camastra.webp', alt: { it: 'Panorama di Santo Stefano di Camastra affacciato sulla costa tirrenica', en: 'Santo Stefano di Camastra overlooking the Tyrrhenian coast', de: 'Santo Stefano di Camastra über der tyrrhenischen Küste' }, credit: 'Giovanni.prinzi', url: 'https://commons.wikimedia.org/wiki/File:Santo_S_panorama.JPG', license: 'CC BY-SA 4.0' },
  { src: '/images/bnb/territorio/stagno-parco-dei-nebrodi.webp', alt: { it: 'Stagno e bosco nel Parco dei Nebrodi', en: 'Woodland pond in the Nebrodi Park', de: 'Waldteich im Nebrodi-Park' }, credit: 'Davide Mauro', url: 'https://commons.wikimedia.org/wiki/File:Stagno_Nebrodi.jpg', license: 'CC BY-SA 4.0' },
];

// Original JPEGs supplied by the owner; WebP derivatives generated by prepare-images.py.
export const territoryImages = [
  { src: '/images/bnb/territorio/fontana-ceramica-mare.webp', alt: { it: 'Fontana con vaso e decorazioni in ceramica sul belvedere affacciato sul mare a Santo Stefano di Camastra', en: 'Fountain with a ceramic vase and tiled decorations overlooking the sea in Santo Stefano di Camastra', de: 'Brunnen mit Keramikvase und Fliesendekor am Meer in Santo Stefano di Camastra' }, caption: { it: 'Ceramiche e orizzonti sul mare', en: 'Ceramics and sea views', de: 'Keramik und Meerblick' } },
  { src: '/images/bnb/territorio/muro-ceramiche-belvedere.webp', alt: { it: 'Muro di piastrelle decorate con disegni e impronte davanti al mare a Santo Stefano di Camastra', en: 'Wall of ceramic tiles with drawings and handprints beside the sea in Santo Stefano di Camastra', de: 'Wand aus Keramikfliesen mit Zeichnungen und Handabdrücken am Meer in Santo Stefano di Camastra' }, caption: { it: 'Storie dipinte sulle maioliche', en: 'Stories painted on tiles', de: 'Geschichten auf Majolika' } },
  { src: '/images/bnb/territorio/villa-italia-ceramiche.webp', alt: { it: 'Giardino di Villa Italia con palme e decorazioni in ceramica a Santo Stefano di Camastra', en: 'Villa Italia garden with palms and ceramic decorations in Santo Stefano di Camastra', de: 'Garten der Villa Italia mit Palmen und Keramikdekor in Santo Stefano di Camastra' }, caption: { it: 'Il verde di Villa Italia', en: 'The gardens of Villa Italia', de: 'Die Gärten der Villa Italia' } },
];

// Selected owner photographs, imported reproducibly from the archived originals.
export const revisionPhotos = {
  kitchen: { src: '/images/bnb/spazi-comuni/cucina-comune-vista-ampia.webp', alt: { it: 'Cucina comune della Dimora dei Ricci con tavolo e zona cottura', en: 'Shared kitchen at La Dimora dei Ricci with a table and cooking area', de: 'Gemeinschaftsküche der Dimora dei Ricci mit Tisch und Kochbereich' } },
  ceramics: { src: '/images/bnb/spazi-comuni/ceramiche-cucina-comune.webp', alt: { it: 'Brocca e bicchieri in ceramica sul tavolo della cucina comune', en: 'Ceramic jug and cups on the shared kitchen table', de: 'Keramikkrug und Becher auf dem Tisch der Gemeinschaftsküche' } },
  rooftops: { src: '/images/bnb/territorio/tetti-e-colline-dalla-dimora.webp', alt: { it: 'Tetti di Santo Stefano di Camastra e colline visti dalla Dimora', en: 'Santo Stefano di Camastra rooftops and hills seen from La Dimora', de: 'Dächer von Santo Stefano di Camastra und Hügel, von der Dimora aus gesehen' } },
  square: { src: '/images/bnb/territorio/piazza-e-locali-dalla-dimora.webp', alt: { it: 'Piazza e locali nel centro di Santo Stefano di Camastra visti dalla Dimora', en: 'Square and cafés in central Santo Stefano di Camastra seen from La Dimora', de: 'Platz und Lokale im Zentrum von Santo Stefano di Camastra, von der Dimora aus gesehen' } },
  location: { src: '/images/bnb/territorio/vista-centro-storico-dalla-dimora.webp', alt: { it: 'Vista sui tetti e sulle vie del centro storico di Santo Stefano di Camastra dalla Dimora', en: 'View of Santo Stefano di Camastra old-town rooftops and streets from La Dimora', de: 'Blick von der Dimora auf Dächer und Straßen der Altstadt von Santo Stefano di Camastra' } },
};
Object.values(revisionPhotos).forEach(photo => { imageSettings[photo.src] = { alt: photo.alt }; });
const bathroomAlts = [
  ['glicine/bagno-glicine-vista-completa', { it: 'Bagno privato della Camera Glicine con lavabo e sanitari', en: 'Private bathroom of the Glicine room with washbasin and sanitary fittings', de: 'Eigenes Bad des Zimmers Glicine mit Waschbecken und Sanitäranlagen' }],
  ['glicine/bagno-glicine-doccia', { it: 'Doccia del bagno privato della Camera Glicine', en: 'Shower in the Glicine room’s private bathroom', de: 'Dusche im eigenen Bad des Zimmers Glicine' }],
  ['papavero/bagno-papavero-doccia-e-lavabo', { it: 'Doccia e lavabo del bagno privato della Camera Papavero', en: 'Shower and washbasin in the Papavero room’s private bathroom', de: 'Dusche und Waschbecken im eigenen Bad des Zimmers Papavero' }],
  ['papavero/bagno-papavero-vista-completa', { it: 'Bagno privato della Camera Papavero con lavabo e sanitari', en: 'Private bathroom of the Papavero room with washbasin and sanitary fittings', de: 'Eigenes Bad des Zimmers Papavero mit Waschbecken und Sanitäranlagen' }],
] as const;
bathroomAlts.forEach(([path, alt]) => { imageSettings[`/images/bnb/camere/${path}.webp`] = { alt }; });

export function roomPhotoAlt(src: string, name: string, language: Language) {
  const custom = imageSettings[src]?.alt?.[language];
  if (custom) return custom;
  const detail = src.includes('/bagno-') ? { it: 'Bagno privato', en: 'Private bathroom', de: 'Eigenes Bad' }
    : src.includes('/terrazza-') ? { it: 'Terrazza di sera', en: 'Terrace in the evening', de: 'Terrasse am Abend' }
    : src.includes('letto-castello') ? { it: 'Letto a castello', en: 'Bunk bed', de: 'Etagenbett' }
    : src.includes('/chiavi-') ? { it: 'Chiavi della camera', en: 'Room keys', de: 'Zimmerschlüssel' }
    : src.includes('/targa-') ? { it: 'Targa della camera', en: 'Room sign', de: 'Zimmerschild' }
    : { it: 'Vista degli interni', en: 'Interior view', de: 'Innenansicht' };
  return `${detail[language]} — ${name}`;
}
